### ISSUE TITLE
Fix node-location extraction in the node table

### ISSUE THREAD

**Issue by alkadi-mh** [networkcube/vistorian-web#12]
In the node table  when the user describes the column as a node location the following error occurs:
<img width="1792" alt="nodeLocation" src="https://user-images.githubusercontent.com/24791589/127282264-c9cb4310-87fe-4e40-bba7-42eb2cb4d483.png">

**Comment by jamesscottbrown** [comment]
This issue was resolved by replacing the old UI with the wizard.
