### ISSUE TITLE
Error occurs when adding both node and link table to a network

### ISSUE THREAD

**Issue by alkadi-mh** [networkcube/vistorian-web#13]
When the user adds a node table to a network that has link table already, the following error occurs:
<img width="1781" alt="node and link table" src="https://user-images.githubusercontent.com/24791589/127283509-e4968de8-0ee0-4281-86af-11a1790726ba.png">

**Comment by jamesscottbrown** [comment]
This issue was resolved by replacing the old UI with the wizard.
