### ISSUE TITLE
Error handling on network-level

### ISSUE THREAD

**Issue by alkadi-mh** [networkcube/vistorian-web#14]
If an error occurs in a network while uploading a node/link table or specifying a column's type, the user cannot proceed with network correctly as it keeps showing error messages even if the user changes the table caused the error. 

<img width="1785" alt="Screen Shot 2021-07-28 at 10 56 32 AM" src="https://user-images.githubusercontent.com/24791589/127285925-850b905f-b2f0-49d3-a3d9-0c6a3c5fc0f9.png">

**Comment by jamesscottbrown** [comment]
This issue was resolved by replacing the old UI with the wizard.
